version: 2

models:      
  - name: fact_covid_symptomes
    description: >
      Fact covid symptomes table, which contains data of the daily and weekly top 5 symptomes of the covid infected people.
    columns:
      - name: country_region_code
        data_type: string
        description: country region code for covid infected

      - name: country_region
        data_type: string
        description: country region by region code for covid infected

      - name: symptom_infection
        data_type: float64
        description: An infection is the invasion of tissues by pathogens, their multiplication, and the reaction of host tissues to the infectious agent and the toxins they produce.

      - name: symptom_itch
        data_type: float64
        description: (also known as pruritus) is a sensation that causes a strong desire or reflex to scratch.

      - name: symptom_pain
        data_type: float64
        description: Pain is a distressing feeling often caused by intense or damaging stimuli.

      - name: symptom_skin_rash
        data_type: float64
        description: A rash is a change of the skin that affects its color, appearance, or texture.

      - name: symptom_allergy
        data_type: float64
        description: Allergies, also known as allergic diseases, are various conditions caused by hypersensitivity of the immune system to typically harmless substances in the environment.
